2023-04-19 16:59:47,418 INFO    MainThread:15716 [wandb_setup.py:_flush():69] setting env: {}
2023-04-19 16:59:47,418 INFO    MainThread:15716 [wandb_setup.py:_flush():69] setting login settings: {}
2023-04-19 16:59:47,419 INFO    MainThread:15716 [wandb_init.py:_log_setup():342] Logging user logs to /home/utente/Scrivania/PROVA/LADD/wandb/run-20230419_165947-1sjmk8rf/logs/debug.log
2023-04-19 16:59:47,419 INFO    MainThread:15716 [wandb_init.py:_log_setup():343] Logging internal logs to /home/utente/Scrivania/PROVA/LADD/wandb/run-20230419_165947-1sjmk8rf/logs/debug-internal.log
2023-04-19 16:59:47,419 INFO    MainThread:15716 [wandb_init.py:init():375] calling init triggers
2023-04-19 16:59:47,419 INFO    MainThread:15716 [wandb_init.py:init():380] wandb.init called with sweep_config: {}
config: {}
2023-04-19 16:59:47,419 INFO    MainThread:15716 [wandb_init.py:init():424] starting backend
2023-04-19 16:59:47,420 INFO    MainThread:15716 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-04-19 16:59:47,437 INFO    MainThread:15716 [backend.py:ensure_launched():135] starting backend process...
2023-04-19 16:59:47,446 INFO    MainThread:15716 [backend.py:ensure_launched():139] started backend process with pid: 15749
2023-04-19 16:59:47,448 INFO    MainThread:15716 [wandb_init.py:init():429] backend started and connected
2023-04-19 16:59:47,449 INFO    MainThread:15716 [wandb_init.py:init():477] updated telemetry
2023-04-19 16:59:47,450 INFO    MainThread:15716 [wandb_init.py:init():500] communicating current version
2023-04-19 16:59:48,647 INFO    MainThread:15716 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.14.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-04-19 16:59:48,647 INFO    MainThread:15716 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2023-04-19 17:00:18,648 INFO    MainThread:15716 [interface.py:_communicate_run():651] couldn't get run from backend
2023-04-19 17:00:18,649 ERROR   MainThread:15716 [wandb_init.py:init():518] backend process timed out
2023-04-19 17:00:18,649 ERROR   MainThread:15716 [wandb_init.py:init():527] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2023-04-19 17:01:26,917 INFO    MainThread:15716 [wandb_init.py:teardown():194] tearing down wandb.init
