Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
dynamic_import - class_name:  OracleClient
Done.
Initializing server...
dynamic_import - class_name:  OracleServer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
dynamic_import - class_name:  OracleClient
The experiment begins...
ROUND 1/15: Training 2 Clients...
CLIENT 1/2: erfurt5 RGB
EPOCH 1: ended.
end
CLIENT 2/2: weimar3 HHA
EPOCH 1: ended.
end
{'Total samples': array(56), 'Overall Acc': 0.3056665218723358, 'Mean Acc': 0.08729517179451883, 'Mean Precision': 0.09269784026457872, 'FreqW Acc': 0.19073505991276987, 'Mean IoU': 0.04575566299293804, 'Class IoU': {0: 0.2738516253022121, 1: 0.13299064553113715, 2: 0.2573199295378051, 3: 0.0, 4: 0.0, 5: 0.012112108912718925, 6: 0.0, 7: 0.0, 8: 0.02899611009787163, 9: 0.0, 10: 0.013390704471487682, 11: 0.00995278638776662, 12: 0.0, 13: 0.0034766976460095084, 14: 'X', 15: 'X', 16: 'X', 17: 0.0, 18: 0.0}, 'Class Acc': {0: 0.4682799578669521, 1: 0.1415890689745718, 2: 0.41050642923528746, 3: 0.0, 4: 0.0, 5: 0.013813463570586673, 6: 0.0, 7: 0.0, 8: 0.03612261675556726, 9: 0.0, 10: 0.25197288370408577, 11: 0.07044339534988228, 12: 0.0, 13: 0.003994933255367846, 14: 'X', 15: 'X', 16: 'X', 17: 0.0, 18: 0.0}, 'Class Prec': {0: 0.39743452211096725, 1: 0.6865143684242484, 2: 0.408130390888925, 3: 0.0, 4: 0.0, 5: 0.08953460900318104, 6: 0.0, 7: 0.0, 8: 0.12814110149237246, 9: 0.0, 10: 0.013945058623860624, 11: 0.01145756485334424, 12: 0.0, 13: 0.02610134963009673, 14: 'X', 15: 'X', 16: 'X', 17: 0.0, 18: 0.0}}
QUI ARRIVA ALL'UPDATE
AGGREGATION: END OF THE ROUND
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 53, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 21, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 136, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 81, in perform_fed_oracle_training
    self.server.update_model()
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 275, in update_model
    if self.optimizer is not None:
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 53, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 21, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 136, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 81, in perform_fed_oracle_training
    self.server.update_model()
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 275, in update_model
    if self.optimizer is not None:
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 275, in update_model
    if self.optimizer is not None:
  File "_pydevd_bundle/pydevd_cython.pyx", line 1589, in _pydevd_bundle.pydevd_cython.ThreadTracer.__call__
  File "_pydevd_bundle/pydevd_cython.pyx", line 929, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 920, in _pydevd_bundle.pydevd_cython.PyDBFrame.trace_dispatch
  File "_pydevd_bundle/pydevd_cython.pyx", line 317, in _pydevd_bundle.pydevd_cython.PyDBFrame.do_wait_suspend
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1160, in do_wait_suspend
    self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread)
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1175, in _do_wait_suspend
    time.sleep(0.01)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2195, in <module>
    main()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2179, in main
    handle_keyboard_interrupt()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1997, in handle_keyboard_interrupt
    traceback.print_exception(type(value), value, tb, limit=limit)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 639, in format
    yield from self.format_exception_only()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 580, in format_exception_only
    yield _format_final_exc_line(stype, self._str)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/traceback.py", line 145, in _format_final_exc_line
    def _format_final_exc_line(etype, value):
KeyboardInterrupt