Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
dynamic_import - class_name:  OracleClient
Done.
Initializing server...
dynamic_import - class_name:  OracleServer
Running without server optimizer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
dynamic_import - class_name:  OracleClient
The experiment begins...
ROUND 1/15: Training 2 Clients...
CLIENT 1/2: erfurt5 RGB
train RGB
EPOCH 1: ended.
CLIENT 2/2: weimar3 HHA
train HHA
EPOCH 1: ended.
length losses_2:  1  length losses_2:   1
length losses_2:  1
['weimar3HHA']
dict_keys(['weimar3HHA'])
{'Total samples': array(32), 'Overall Acc': 0.10344827586206896, 'Mean Acc': 0.07142857047902496, 'Mean Precision': 0.03508771832358677, 'FreqW Acc': 0.0743745767130532, 'Mean IoU': 0.0509803916752104, 'Class IoU': {0: 0.08823529325259517, 1: 0.0, 2: 0.16666666512345682, 3: 'X', 4: 'X', 5: 'X', 6: 'X', 7: 'X', 8: 0.0, 9: 'X', 10: 0.0, 11: 'X', 12: 'X', 13: 'X', 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 'X'}, 'Class Acc': {0: 0.10714285586734695, 1: 0.0, 2: 0.24999999652777782, 3: 'X', 4: 'X', 5: 'X', 6: 'X', 7: 'X', 8: 0.0, 9: 'X', 10: 0.0, 11: 'X', 12: 'X', 13: 'X', 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 'X'}, 'Class Prec': {0: 0.3333333209876548, 1: 0.0, 2: 0.33333332716049396, 3: 'X', 4: 'X', 5: 'X', 6: 'X', 7: 'X', 8: 0.0, 9: 'X', 10: 0.0, 11: 'X', 12: 'X', 13: 'X', 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 'X'}}
 length losses_2:   1
['erfurt5RGB']
dict_keys(['erfurt5RGB'])
{'Total samples': array(16), 'Overall Acc': 0.0, 'Mean Acc': 0.0, 'Mean Precision': 0.0, 'FreqW Acc': 0.0, 'Mean IoU': 0.0, 'Class IoU': {0: 0.0, 1: 0.0, 2: 0.0, 3: 'X', 4: 'X', 5: 'X', 6: 'X', 7: 'X', 8: 0.0, 9: 'X', 10: 0.0, 11: 'X', 12: 'X', 13: 0.0, 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 'X'}, 'Class Acc': {0: 0.0, 1: 0.0, 2: 0.0, 3: 'X', 4: 'X', 5: 'X', 6: 'X', 7: 'X', 8: 0.0, 9: 'X', 10: 0.0, 11: 'X', 12: 'X', 13: 0.0, 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 'X'}, 'Class Prec': {0: 0.0, 1: 0.0, 2: 0.0, 3: 'X', 4: 'X', 5: 'X', 6: 'X', 7: 'X', 8: 0.0, 9: 'X', 10: 0.0, 11: 'X', 12: 'X', 13: 0.0, 14: 'X', 15: 'X', 16: 'X', 17: 'X', 18: 'X'}}
QUI ARRIVA ALL'UPDATE
AGGREGATION: END OF THE ROUND
ROUND 2/15: Training 2 Clients...
CLIENT 1/2: dusseldorf4 HHA
train HHA
EPOCH 1: ended.
CLIENT 2/2: dusseldorf1 HHA
train HHA
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 51, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 20, in run_experiment
    max_score,max_score_2 = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 103, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 43, in perform_fed_oracle_training
    losses, losses_2 = self.server.train_clients(partial_metric=partial_train_metric,  partial_metric_2=partial_train_metric_2)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 49, in train_clients
    out = c.train(partial_metric, r=r)
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 199, in train
    dict_all_iters_losses = self.run_epoch(epoch, optimizer, metric=partial_metric, r=r)
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 169, in run_epoch
    self.__exec_epoch(optimizer, cur_epoch, metric, scheduler, plot_lr, dict_all_iters_losses,
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 91, in __exec_epoch
    for cur_step, samples in enumerate(self.loader):
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1142, in _get_data
    success, data = self._try_get_data()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2195, in <module>
    main()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 2179, in main
    handle_keyboard_interrupt()
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1996, in handle_keyboard_interrupt
    value.__cause__ = None
KeyboardInterrupt