Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Traceback (most recent call last):
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/utente/pycharm/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 53, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 15, in run_experiment
    trainer = trainer_class(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 8, in __init__
    super().__init__(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/trainer.py", line 11, in __init__
    super().__init__(args, writer, device, rank, world_size)
  File "/home/utente/Scrivania/PROVA/LADD/src/general_trainer.py", line 38, in __init__
    self.model = self.model_init(args, device)
  File "/home/utente/Scrivania/PROVA/LADD/src/general_trainer.py", line 112, in model_init
    model = make_model(args)
  File "/home/utente/Scrivania/PROVA/LADD/src/utils/model_utils.py", line 100, in make_model
    return dict_model[args.model]['model'](args.num_classes, **dict_model[args.model]['kwargs'])
  File "/home/utente/Scrivania/PROVA/LADD/src/modules/deeplabv3.py", line 71, in multi_deeplabv3_mobilenetv2
    rgb_backbone = MobileNetV2(width_mult=width_mult, in_channels=in_channels)
  File "/home/utente/Scrivania/PROVA/LADD/src/modules/deeplabv3.py", line 15, in __init__
    self.model = mobilenet_v2(pretrained=pretrained, **kwargs)
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torchvision/models/mobilenetv2.py", line 192, in mobilenet_v2
    model = MobileNetV2(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'in_channels'