Done.
Setting up the random seed for reproducibility...
Done.
dynamic_import - class_name:  OracleTrainer
Initializing model...
Done.
Initializing datasets...
Done.
Initializing clients...
dynamic_import - class_name:  OracleClient
Done.
Initializing server...
dynamic_import - class_name:  OracleServer
Running without server optimizer
Done.
Initialize return score, metrics, ckpt, ckpt step...
Setting up metrics...
Done.
Done.
Initializing optimizer and scheduler...
Done.
dynamic_import - class_name:  OracleClient
The experiment begins...
ROUND 1/5: Training 2 Clients...
CLIENT 1/2: erfurt5 RGB
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f9626595b80>
Traceback (most recent call last):
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1328, in __del__
    self._shutdown_workers()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1288, in _shutdown_workers
    self._workers_done_event.set()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/multiprocessing/synchronize.py", line 335, in set
    with self._cond:
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/multiprocessing/synchronize.py", line 230, in __enter__
    return self._lock.__enter__()
  File "/home/utente/anaconda3/envs/LADD/lib/python3.9/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt:
Traceback (most recent call last):
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 53, in <module>
    run_experiment()
  File "/home/utente/Scrivania/PROVA/LADD/src/run.py", line 21, in run_experiment
    max_score = trainer.train(*trainer.train_args, **trainer.train_kwargs)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 136, in train
    return self.perform_fed_oracle_training(
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/trainers/oracle_trainer.py", line 76, in perform_fed_oracle_training
    losses = self.server.train_clients(partial_metric=partial_train_metric)
  File "/home/utente/Scrivania/PROVA/LADD/src/federated/servers/oracle_server.py", line 101, in train_clients
    out = c.train(partial_metric, r=r)
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 200, in train
    dict_all_iters_losses = self.run_epoch(epoch, optimizer, metric=partial_metric, r=r)
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 170, in run_epoch
    self.__exec_epoch(optimizer, cur_epoch, metric, scheduler, plot_lr, dict_all_iters_losses,
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/oracle_client.py", line 150, in __exec_epoch
    self.update_metric(metric, outputs, labels)
  File "/home/utente/Scrivania/PROVA/LADD/src/clients/client.py", line 92, in update_metric
    metric.update(labels, prediction)
  File "/home/utente/Scrivania/PROVA/LADD/src/metrics/stream_metrics.py", line 25, in update
    self.confusion_matrix += self._fast_hist(lt.flatten(), lp.flatten())
  File "/home/utente/Scrivania/PROVA/LADD/src/metrics/stream_metrics.py", line 18, in _fast_hist
    self.n_classes * label_true[mask].astype(int) + label_pred[mask],
KeyboardInterrupt